-- MySQL Script generated by MySQL Workbench
-- Sun Dec 18 23:16:34 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema clyck
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema clyck
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `clyck` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `clyck` ;

-- -----------------------------------------------------
-- Table `clyck`.`state`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clyck`.`state` (
  `state_id` INT NOT NULL AUTO_INCREMENT,
  `state_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`state_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clyck`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clyck`.`city` (
  `city_id` INT(11) NOT NULL AUTO_INCREMENT,
  `city_name` VARCHAR(100) NOT NULL,
  `city_state_id` INT NOT NULL,
  PRIMARY KEY (`city_id`),
  INDEX `fk_city_state_idx` (`city_state_id` ASC),
  CONSTRAINT `fk_city_state`
    FOREIGN KEY (`city_state_id`)
    REFERENCES `clyck`.`state` (`state_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `clyck`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clyck`.`user` (
  `user_id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(45) NOT NULL,
  `user_password` VARCHAR(45) NOT NULL,
  `user_active` TINYINT(1) NOT NULL DEFAULT '1',
  `user_type` ENUM('Administrador', 'Gerente', 'Supervisor', 'Atendente') NOT NULL,
  `user_login_default` TINYINT(1) NOT NULL DEFAULT '1',
  `user_id_active` INT(11) NULL DEFAULT NULL,
  `user_date_active` TIMESTAMP NULL DEFAULT NULL,
  `user_id_deactivate` INT(11) NULL DEFAULT NULL,
  `user_date_deactivate` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `clyck`.`event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clyck`.`event` (
  `event_id` INT(11) NOT NULL,
  `event_name` VARCHAR(45) NOT NULL,
  `event_initial_date` TIMESTAMP NOT NULL,
  `event_final_date` TIMESTAMP NULL,
  `event_image` VARCHAR(255) NULL DEFAULT NULL,
  `event_state_id` INT NOT NULL,
  `event_city_id` INT(11) NOT NULL,
  `latitude` DOUBLE NULL DEFAULT NULL,
  `longitude` DOUBLE NULL DEFAULT NULL,
  `event_description` VARCHAR(255) NULL DEFAULT NULL,
  `event_tax_service` DECIMAL(10,2) NULL DEFAULT NULL,
  `event_user_id` INT NOT NULL,
  PRIMARY KEY (`event_id`),
  INDEX `fk_event_city_idx` (`event_city_id` ASC),
  INDEX `fk_event_user_idx` (`event_user_id` ASC),
  INDEX `fk_event_state_idx` (`event_state_id` ASC),
  CONSTRAINT `fk_event_city`
    FOREIGN KEY (`event_city_id`)
    REFERENCES `clyck`.`city` (`city_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_event_user`
    FOREIGN KEY (`event_user_id`)
    REFERENCES `clyck`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_event_state`
    FOREIGN KEY (`event_state_id`)
    REFERENCES `clyck`.`state` (`state_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `clyck`.`coupon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clyck`.`coupon` (
  `coupon_id` INT(11) NOT NULL AUTO_INCREMENT,
  `coupon_number` VARCHAR(45) NOT NULL,
  `coupon_tax` FLOAT NULL DEFAULT NULL,
  `coupon_sin_used` TINYINT(1) NULL DEFAULT '0',
  `coupon_event_id` INT(11) NULL DEFAULT NULL,
  `coupon_user_id` INT NOT NULL,
  PRIMARY KEY (`coupon_id`),
  INDEX `fk_coupon_event_idx` (`coupon_event_id` ASC),
  INDEX `fk_coupon_user_idx` (`coupon_user_id` ASC),
  CONSTRAINT `fk_coupon_event`
    FOREIGN KEY (`coupon_event_id`)
    REFERENCES `clyck`.`event` (`event_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_coupon_user`
    FOREIGN KEY (`coupon_user_id`)
    REFERENCES `clyck`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `clyck`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clyck`.`customer` (
  `customer_id` INT(11) NOT NULL AUTO_INCREMENT,
  `customer_first_name` VARCHAR(45) NOT NULL,
  `customer_last_name` VARCHAR(45) NOT NULL,
  `customer_email` VARCHAR(100) NOT NULL,
  `customer_password` VARCHAR(45) NULL DEFAULT NULL,
  `customer_birthday` TIMESTAMP NULL,
  `customer_phone` VARCHAR(20) NULL DEFAULT NULL,
  `customer_cpf` VARCHAR(45) NULL,
  `customer_stripe` VARCHAR(255) NULL,
  `customer_token` VARCHAR(100) NULL DEFAULT NULL,
  `customer_device_id` VARCHAR(45) NULL DEFAULT NULL,
  `customer_registration_date` TIMESTAMP NULL DEFAULT NULL,
  `customer_sin_valid` TINYINT(1) NULL DEFAULT '1',
  PRIMARY KEY (`customer_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 29
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `clyck`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clyck`.`order` (
  `order_id` INT(11) NOT NULL AUTO_INCREMENT,
  `order_customer_id` INT(11) NOT NULL,
  `order_customer_email` VARCHAR(150) NOT NULL,
  `order_tracking_number` VARCHAR(20) NOT NULL,
  `order_date` TIMESTAMP NOT NULL,
  `order_price` DECIMAL(10,2) NOT NULL,
  `order_price_discount` DECIMAL(10,2) NULL DEFAULT NULL,
  `order_tax_service` DECIMAL(10,2) NULL DEFAULT NULL,
  `order_price_total` DECIMAL(10,2) NOT NULL,
  `order_schedule_date` TIME NULL DEFAULT NULL,
  `order_delivery_date` TIMESTAMP NULL DEFAULT NULL,
  `order_coupon_id` INT(11) NULL DEFAULT NULL,
  `order_event_id` INT(11) NOT NULL,
  `order_status` ENUM('complete', 'processing', 'pending', 'failed') NULL DEFAULT NULL,
  `order_user_id_delivery` INT(11) NULL DEFAULT NULL,
  `order_vote_buying` ENUM('1','2','3','4','5') NULL DEFAULT NULL,
  PRIMARY KEY (`order_id`),
  INDEX `fk_order_user_idx` (`order_customer_id` ASC),
  INDEX `fk_order_coupon_idx` (`order_coupon_id` ASC),
  INDEX `fk_order_event_idx` (`order_event_id` ASC),
  INDEX `order_user_id_delivery` (`order_user_id_delivery` ASC),
  CONSTRAINT `fk_order_coupon`
    FOREIGN KEY (`order_coupon_id`)
    REFERENCES `clyck`.`coupon` (`coupon_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_order_customer`
    FOREIGN KEY (`order_customer_id`)
    REFERENCES `clyck`.`customer` (`customer_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_order_event`
    FOREIGN KEY (`order_event_id`)
    REFERENCES `clyck`.`event` (`event_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 210
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `clyck`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clyck`.`product` (
  `product_id` INT(11) NOT NULL AUTO_INCREMENT,
  `product_name` VARCHAR(100) NOT NULL,
  `product_price` DECIMAL(10,2) NOT NULL,
  `product_image` VARCHAR(45) NULL DEFAULT NULL,
  `product_short_desc` VARCHAR(255) NOT NULL,
  `product_long_desc` TEXT NOT NULL,
  `product_event_id` INT(11) NOT NULL,
  `product_inventory_qtd` INT(11) NOT NULL,
  `product_inventory_current` INT(11) NOT NULL,
  `product_user_id` INT NULL,
  `product_date` TIMESTAMP NULL,
  PRIMARY KEY (`product_id`),
  INDEX `fk_product_event_idx` (`product_event_id` ASC),
  INDEX `fk_product_user_idx` (`product_user_id` ASC),
  CONSTRAINT `fk_product_event`
    FOREIGN KEY (`product_event_id`)
    REFERENCES `clyck`.`event` (`event_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_product_user`
    FOREIGN KEY (`product_user_id`)
    REFERENCES `clyck`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 230
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `clyck`.`item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clyck`.`item` (
  `item_id` INT(11) NOT NULL AUTO_INCREMENT,
  `item_order_id` INT(11) NOT NULL,
  `item_product_id` INT(11) NOT NULL,
  `item_price_unit` DECIMAL(10,2) NOT NULL,
  `item_quantity` INT(11) NOT NULL,
  `item_price_total` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`item_id`),
  INDEX `fk_item_order_idx` (`item_order_id` ASC),
  INDEX `fk_item_product_idx` (`item_product_id` ASC),
  CONSTRAINT `fk_item_order`
    FOREIGN KEY (`item_order_id`)
    REFERENCES `clyck`.`order` (`order_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_item_product`
    FOREIGN KEY (`item_product_id`)
    REFERENCES `clyck`.`product` (`product_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 253
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `clyck`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clyck`.`status` (
  `status_id` INT(11) NOT NULL AUTO_INCREMENT,
  `status_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`status_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `clyck`.`auth`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clyck`.`auth` (
  `auth_id` INT NOT NULL AUTO_INCREMENT,
  `auth_customer_id` INT NOT NULL,
  `auth_type` ENUM('facebook', 'google') NOT NULL,
  `auth_value` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`auth_id`),
  INDEX `fk_auth_customer_idx` (`auth_customer_id` ASC),
  CONSTRAINT `fk_auth_customer`
    FOREIGN KEY (`auth_customer_id`)
    REFERENCES `clyck`.`customer` (`customer_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clyck`.`payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clyck`.`payment` (
  `payment_id` INT NOT NULL AUTO_INCREMENT,
  `payment_stripe` VARCHAR(255) NOT NULL,
  `payment_description` VARCHAR(45) NOT NULL,
  `payment_last4` VARCHAR(4) NOT NULL,
  `payment_customer_id` INT NOT NULL,
  `payment_active` TINYINT(1) NULL DEFAULT 1,
  `payment_date` TIMESTAMP NULL,
  PRIMARY KEY (`payment_id`),
  INDEX `fk_payment_customer_idx` (`payment_customer_id` ASC),
  CONSTRAINT `fk_payment_customer`
    FOREIGN KEY (`payment_customer_id`)
    REFERENCES `clyck`.`customer` (`customer_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clyck`.`transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clyck`.`transaction` (
  `transaction_id` INT NOT NULL AUTO_INCREMENT,
  `transaction_customer_id` INT NOT NULL,
  `transaction_payment_id` INT NOT NULL,
  `transaction_charge` VARCHAR(255) NULL,
  `transaction_amount` VARCHAR(45) NOT NULL,
  `transaction_date` TIMESTAMP NOT NULL,
  PRIMARY KEY (`transaction_id`),
  INDEX `fk_payment_customer_idx` (`transaction_customer_id` ASC),
  INDEX `fk_payment_payment_idx` (`transaction_payment_id` ASC),
  CONSTRAINT `fk_payment_customer`
    FOREIGN KEY (`transaction_customer_id`)
    REFERENCES `clyck`.`customer` (`customer_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_payment_payment`
    FOREIGN KEY (`transaction_payment_id`)
    REFERENCES `clyck`.`payment` (`payment_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
